// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden/pkg/resource"
	"raidencommerce/internal/models"
)

func RegisterModels() {
	resource.RegisterModels(
		&models.Order{},
		&models.Orderitem{},
		&models.Product{},
		&models.Productcategory{},
	)
}
