// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden"
	"raidencommerce/internal/controllers"
	"raidencommerce/internal/models"
	"github.com/valyala/fasthttp"
)

func RegisterRoute(server *raiden.Server) {
	server.RegisterRoute([]*raiden.Route{
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/hello/{name}",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.HelloWordController{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/orders",
			Methods:    []string{},
			Controller: &controllers.OrderController{},
			Model:      models.Order{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/orderitems",
			Methods:    []string{},
			Controller: &controllers.OrderitemController{},
			Model:      models.Orderitem{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/products",
			Methods:    []string{},
			Controller: &controllers.ProductController{},
			Model:      models.Product{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/product-categories",
			Methods:    []string{},
			Controller: &controllers.ProductCategoryController{},
			Model:      models.Productcategory{},
		},
	})
}
